# Generated by Django 2.1 on 2019-04-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('ssex', models.BooleanField()),
                ('scontent', models.CharField(max_length=200)),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.classInfo')),
            ],
        ),
    ]
